### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/xorhub-serverscontents#1]
I think now that we included server-configuration files into the repository, we shall rename the repository from **xorhub-mapcontents** to **xorhub-server****_(s)**_**contents**

**Comment by BetterToAutomateTheWorld** [comment]
I agree, you can tweak the name of the repository when you want

**Comment by ObaniGemini** [comment]
Done https://github.com/MinetestForFun/xorhub-serverscontents/commit/4b9d3e5edd67cd5b6d96f9ea68c2192f0349cc3f
