### ISSUE TITLE
Replace IP adress to DNS adress on xorhub.com

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/xorhub-serverscontents#3]
Some pages still use the IP adress of the new server instead of the DNS name :
- Warsow server :
  - [x] [FR](https://xorhub.com/fr/warsow-server/)
  - [x] [EN](https://xorhub.com/en/warsow-server/)
- Teeworlds server :
  - [x] [FR](https://xorhub.com/fr/teeworlds-server/)
  - [x] [EN](https://xorhub.com/en/teeworlds-server/)

**Comment by BetterToAutomateTheWorld** [comment]
Good idea, thank you for the issue!
- [x] Warsow FR / EN (replace the IP address for the FQDN address)
- [x] TeeWorlds FR / EN (only FQDN now)
- [x] Minetest FR / EN (only FQDN now)
