### ISSUE TITLE
Create a forum

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/xorhub-serverscontents#4]
@ObaniGemini wants a forum, it's a good idea, i create a forum based on Flarum available here : http://forum.xorhub.com/ (http://xorhub.com/forum/ redirect to http://forum.xorhub.com/)

No HTTPS access for the moment, it will be available in HTTPS in the next 2 months (I added it to the certificates refresh every 3 months on the crontab execution script, we just need to wait :))

**Comment by BetterToAutomateTheWorld** [comment]
Done http://forum.xorhub.com

This will maybe interest some people : @Cyberpangolin @crabman77 @LeMagnesium etc.

PS : maybe we could add a random message to invite players to go to the forum ?

**Comment by ObaniGemini** [comment]
Did I ever say that ?
The answer is : no
I remember talking about a forum one time on IRC and it was just a blabbering around Tremulous

P.S : not that I find it a bad idea, I just don't like it that you quote me this way.

**Comment by BetterToAutomateTheWorld** [comment]
Well, I see some people (you included) to ask that since a long time.
I remember your name in the group of peoples that want it. Don't took it badly like this, it's not a complain about you...

To be clear, because I find your answer a little unpleasant and to prove that I am not a liar : 

> [11:52:32] Obani> MinetestForFun,
> [11:52:40] Obani> J'ai une question
> [11:52:44] Obani> très sérieuse
> [11:52:53] Obani> Et difficile
> [11:53:36] MinetestForFun> Obani, pose là je répond quand j'ai le temps :)
> [11:53:36] Obani> A-t-on les moyen d'héberger un forum ?:s
> [11:53:39] Obani> MinetestForFun, 
> [11:53:56] MinetestForFun> ah oui carrément, on peut, mais la modération ça prend un temps fou
> [11:54:31] Obani> MinetestForFun, grangerh[...]
> [11:57:03] MinetestForFun> j'ai récemment mis ça en place : https://batocera-linux.xorhub.com/forum/
> [11:57:06] SamBot> Title: batocera.linux - forum (at batocera-linux.xorhub.com)
> [11:57:40] MinetestForFun> Bon ducoup il nous faut notre propre instance, mais j'en réinstalle un quand tu veux, c'est assez simple, fonctionnel, moderne
> [11:58:07] MinetestForFun> j'afk me chercher a manger
> [12:00:46] Obani> en tous cas c'est long à charger
> [12:00:57] Obani> ouais c'est discourse aussi
> [...]
> [12:01:39] MinetestForFun> c'est pas discourse, discourse c'est super lourd :p
> [12:01:51] MinetestForFun> là c'est du php javascript, ça s'update avec composer, c'est cool :)

**Comment by ObaniGemini** [comment]
`<Obani> MinetestForFun, grangerh[...]`

I didn't say you were a liar, I stated when I said it. Which was off-topic compared to what you said in the post.

Also I don't like it to be spotted there if there are some other people asking for it.
Also I quitted Tremulous.
Also don't think I'm that kind of guy which is stable on their positions.

**Comment by BetterToAutomateTheWorld** [comment]
This message I hided was just about the fact you dislike the community of this forum, not the fact you want a forum for this game. 

I don't understand where is the point you here... Just contact me on IRC, it will be maybe more productive :)

**Comment by BetterToAutomateTheWorld** [comment]
I added a Forum information and guidelines "post-it" and "locked" thread in the "general" section of the forum to explain some basic rules and concept of the forum : http://forum.xorhub.com/d/1-forum-information-and-guidelines
